# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0a20ed535cb8dd536ccf78e2b025407cdd58f4b3286a89908487048f8a7d0e4b59117a3c5fed96e109a539a511adcf0f6c6942f1f609e12005139bdea2c688e

test:
  secret_key_base: b4e0dbb71bfc8cce1abeb520d7200b25809e33402884a46264ac6061a866e582936d11b18c88957ed7578301645b16fbb876bc16960f2b85e73653508358b5f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
